{% set version = "11.0.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tsdyn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tsDyn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tsDyn/tsDyn_{{ version }}.tar.gz
  sha256: e748c601827920fbaefa7c3d9f9f2fce0e91726d56bdb58dfc5180815c81c06c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach
    - r-forecast
    - r-mass
    - r-matrix
    - r-mgcv
    - r-mnormt
    - r-nnet
    - r-tseries
    - r-tserieschaos
    - r-urca
    - r-vars
  run:
    - r-base
    - r-foreach
    - r-forecast
    - r-mass
    - r-matrix
    - r-mgcv
    - r-mnormt
    - r-nnet
    - r-tseries
    - r-tserieschaos
    - r-urca
    - r-vars

test:
  commands:
    - $R -e "library('tsDyn')"           # [not win]
    - "\"%R%\" -e \"library('tsDyn')\""  # [win]

about:
  home: https://github.com/MatthieuStigler/tsDyn/wiki
  home: https://github.com/MatthieuStigler/tsDyn
  license: GPL-2.0-or-later
  summary: 'Implements nonlinear autoregressive (AR) time series models. For univariate series, a non-parametric approach is available through additive nonlinear AR. Parametric modeling and testing for regime switching dynamics is available when the transition is either direct (TAR: threshold AR) or smooth (STAR: smooth
    transition AR, LSTAR). For multivariate series, one can estimate a range of TVAR or threshold cointegration TVECM models with two or three regimes. Tests can be conducted for TVAR as well as for TVECM (Hansen and Seo 2002 and Seo 2006).'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - SulphurFH
